config/routes.rb
Rails.application.routes.draw do
  resources :comments
  resources :photos
  devise_for :users
  get "home/index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  root "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :photo

  validates :content, presence: true
end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :user
  has_many :comments

  has_one_attached :image
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :comments, dependent: :destroy 
  has_one_attached :avatar

  validate :avatar_presence, unless: :karina?

  enum role: [:registrado, :karina]

  private

  def avatar_presence
    errors.add(:avatar, "Debe estar presente") unless avatar.attached?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
  
  
  
  protected
  
  def after_sign_in_path_for(resourse)
    photos_path
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :avatar])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :avatar])
  end

    def soy_karina?
    if user_signed_in? && current_user.karina?
      redirect_to root_path, notice: "No tienes permiso para realizar esta acción. Por favor inicia sesión o registrate" 
      end
    end
  
  def soy_registrado?
    if user_signed_in? && current_user.registrado?
      redirect_to root_path, notice: "No tienes permiso para realizar esta acción. Por favor inicia sesión o registrate"
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: %i[ index show ]
  before_action :soy_registrado?, except: %i[ index show new edit create update ]
  before_action :soy_karina?, except: %i[ index show new edit create update destroy ]


  # GET /comments or /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1 or /comments/1.json
  def show
    @comment = Comment.find(params[:id])
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments or /comments.json
  def create
    @comment = Comment.new(comment_params)
    @comment.user = current_user

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @comment, notice: "Comment was successfully created." }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1 or /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: "Comment was successfully updated." }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1 or /comments/1.json
  def destroy
    @comment.destroy!

    respond_to do |format|
      format.html { redirect_to comments_path, status: :see_other, notice: "Comment was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def comment_params
      params.require(:comment).permit(:content, :user_id, :photo_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :set_photo, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: %i[ index show ]
  before_action :redirect_si_user_no_coincide_con_creador_de_la_photo, only: %i[ edit update destroy]
  before_action :soy_karina?, except: %i[ index show new edit create update destroy ]

  # GET /photos or /photos.json
  def index
    @photos = Photo.all
  end

  # GET /photos/1 or /photos/1.json
  def show
    @comments = @photo.comments
  end

  # GET /photos/new
  def new
    @photo = Photo.new
  end

  # GET /photos/1/edit
  def edit
  end

  # POST /photos or /photos.json
  def create
    @photo = Photo.new(photo_params)
    @photo.user = current_user

    respond_to do |format|
      if @photo.save
        format.html { redirect_to @photo, notice: "Photo was successfully created." }
        format.json { render :show, status: :created, location: @photo }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /photos/1 or /photos/1.json
  def update
    respond_to do |format|
      if @photo.update(photo_params)
        format.html { redirect_to @photo, notice: "Photo was successfully updated." }
        format.json { render :show, status: :ok, location: @photo }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /photos/1 or /photos/1.json
  def destroy
    @photo.destroy!

    respond_to do |format|
      format.html { redirect_to photos_path, status: :see_other, notice: "Photo was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_photo
      @photo = Photo.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def photo_params
      params.require(:photo).permit(:image, :content, :user_id)
    end

    def redirect_si_user_no_coincide_con_creador_de_la_photo
      if current_user.id != @photo.user_id
        redirect_to photos_path, notice: "No puedes hacer eso pillin!"
      end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/comments/_comment.html.erb
<div id="<%= dom_id comment %>">
  <p>
    <strong>Comentario: </strong>
    <%= comment.content %>
  </p>

  <p>
    <strong>Usuario: </strong>
    <%= comment.user_id %>
  </p>

  <p>
    <strong>Publicación: </strong>
    <%= comment.photo_id %>
  </p>

</div>

app/views/comments/_form.html.erb
<%= form_with(model: comment) do |f| %>
  <% if comment.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
        <% comment.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= f.label :content, style: "display: block", class: "form-label" %>
    <%= f.text_area :content, class: "form-control" %>
  </div>

  <div>
    <%= f.label :photo_id, style: "display: block", class: "form-label" %>
    <%= f.collection_select(:photo_id, Photo.all, :id, :id, { prompt: "Seleccione una foto" }, class: "form-control") %> 
  </div>

  <div>
    <%= f.submit "Crear Comentario", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<% content_for :title, "Editing comment" %>

<h1 Class="text-center my-3">Editar Comentario</h1>

<%= render "form", comment: @comment %>

<br>

<div>
  <%= link_to "Volver a Comentarios", comments_path, class: "btn btn-secondary" %>
</div>

app/views/comments/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Comments" %>

<div class="card">
  <h1 class="card-header text-center">Comentarios</h1>
</div>

<% @comments.each do |comment| %>
  <div class="card mb-3">
    <div class="row g-0">
      <div class="col-md-2">
        <%= image_tag comment.user.avatar, class: "avatar-img", style:"height: 200px;" %>
      </div>
      <div class="col-md-8">
        <div class="card-body">
          <h5 class="card-title"><%= comment.user.name %></h5>
          <p class="card-text"><%= comment.content %></p>
          <%= link_to "Ver comentario", comment, class: "btn btn-primary" %>
        </div>
      </div>
    </div>
  </div> 
<% end %>

<div class="my-3">
  <%= link_to "Volver a Fotos", photos_path, class: "btn btn-secondary" %>
</div>

app/views/comments/new.html.erb
<% content_for :title, "New comment" %>

<h1>Nuevo Commentario</h1>

<%= render "form", comment: @comment %>

<br>

<div>
  <%= link_to "Volver a comentarios", comments_path, class: "btn btn-secondary" %>
</div>

app/views/comments/show.html.erb
<p style="color: green"><%= notice %></p>


<div class="card mb-3">
  <div class="row g-0">
    <div class="col-md-2">
      <%= image_tag @comment.user.avatar, class: "avatar-img", style:"height: 200px;" %>
    </div>
    <div class="col-md-8">
      <div class="card-body">
        <h5 class="card-title"><%= @comment.user.name %></h5>
        <p class="card-text"><%= @comment.content %></p>
      </div>
    </div>
  </div>
</div> 

<div class="row">
  <div class="col">
    <%= link_to "Volver a Comentarios", comments_path, class:"btn btn-secondary" %>
  </div>
  <div class="col d-flex justify-content-end">
    <% if current_user %>
      <% if current_user == @comment.user || current_user.karina? %>
        <%= link_to "Editar Comentario", edit_comment_path(@comment), class: "btn btn-warning mx-3" %> 
        <%= button_to "Destruir Comentario", @comment, method: :delete, class: "btn btn-danger" %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/home/index.html.erb
<div class="container text-center my-5">
  <div class="card">
    <div class="card-body">
      <h1 class="card-title text-dark mb-4"><strong>Bienvenido a <em>KariPic</em></strong></h1>
      <p class="card-text fs-5">
        ¡Explora el arte de la fotografía como nunca antes!  
        En <strong><em>KariPic</em></strong>, te presentamos las emociones y momentos capturados por la lente de Karina, una fotógrafa de renombre mundial. Disfruta de su talento y sé parte de esta comunidad apasionada por el arte visual.
      </p>
      <hr class="my-4">
        <p class="bi bi-eye text-success"></p> <strong>No estás registrado:</strong> Descubre las fotografías y explora los detalles detrás de cada obra.
        <p class="bi bi-chat-dots text-info"></p> <strong>Tienes una cuenta:</strong> Únete a la conversación dejando comentarios en las fotografías que más te inspiren.
        <hr>
      <%= link_to "Explorar Fotografías", photos_path, class:"btn btn-dark mt-3 px-5", ariaCurrent:"page" %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Karipic" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <% if flash[:notice] %>
       <p class="alert"><%= flash[:notice] %></p>
    <% end %>
    <div class="container">
       <%= yield %>
    </div>


    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js" integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy" crossorigin="anonymous"></script>
  </body>
</html>

app/views/photos/_form.html.erb
<% if current_user.karina? %>
  <%= form_with(model: photo, local: true, html: { class: "needs-validation", novalidate: true }) do |form| %>
    <% if photo.errors.any? %>
      <div class="alert alert-danger">
        <h4 class="alert-heading">
          <%= pluralize(photo.errors.count, "error") %> impidió que esta foto se guardara:
        </h4>
        <ul>
          <% photo.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="mb-3">
      <%= form.label :image, "Foto", class: "form-label" %>
      <%= form.file_field :image, class: "form-control", id: "formFileMultiple" %>
    </div>

    <div class="mb-3">
      <%= form.label :content, "Descripción", class: "form-label" %>
      <%= form.text_area :content, class: "form-control", rows: 3, placeholder: "Agrega una descripción para la foto..." %>
    </div>

    <div class="d-grid gap-2">
      <%= form.submit "Guardar Foto", class: "btn btn-primary btn-block" %>
    </div>
  <% end %>
<% else %>
  <p>Solo Karina puede subir fotos. Si eres Karina, asegúrate de estar autenticada correctamente.</p>
<% end %>

app/views/photos/_photo.html.erb
<div id="<%= dom_id photo %>">
  <p>
    <strong>Image:</strong>
    <%= photo.image %>
  </p>

  <p>
    <strong>Content:</strong>
    <%= photo.content %>
  </p>

  <p>
    <strong>User:</strong>
    <%= photo.user_id %>
  </p>

</div>

app/views/photos/edit.html.erb
<% content_for :title, "Editing photo" %>

<h1>Editing photo</h1>

<%= render "form", photo: @photo %>

<br>

<div>
  <%= link_to "Show this photo", @photo %> |
  <%= link_to "Back to photos", photos_path %>
</div>

app/views/photos/index.html.erb
<% content_for :title, "Posts" %>

<h1 class="text-center my-5">Publicaciones</h1>

<% if user_signed_in? && current_user.karina? %>
  <div class="mb-5 d-flex justify-content-start my-2">
    <%= link_to "Nueva Publicación", new_photo_path, class: "btn btn-success" %>
  </div>
<% end %>

<% if notice %>
  <div class="alert alert-success text-center">
    <%= notice %>
  </div>
<% end %>

<div class="row">
  <% @photos.each do |photo| %>
    <div class="card col-md-4">
      <%= image_tag photo.image, class: "card-img-top img-fluid" %>
      <div class="card-body">
        <p class="card-text text-center"><%= truncate(photo.content, length: 100) %></p>
      </div>
      <div class="card-footer text-center">
        <%= link_to "Ver esta foto", photo_path(photo), class: "btn btn-primary btn-sm" %>
      </div>
    </div>
  <% end %>
</div>

<% if user_signed_in? && current_user.karina? %>
  <div class="mb-5 d-flex justify-content-end my-2">
    <%= link_to "Nueva Publicación", new_photo_path, class: "btn btn-success" %>
  </div>
<% end %>

app/views/photos/new.html.erb
<% content_for :title, "New photo" %>

<h1 class="text-center my-3">Nueva Publicación</h1>

<%= render "form", photo: @photo %>

<br>

<div>
  <%= link_to "Back to photos", photos_path, class: "btn btn-secondary" %>
</div>

app/views/photos/show.html.erb
<p style="color: green"><%= notice %></p>

<div class="my-4 d-flex justify-content-end">
  <%= link_to "Volver a Publicaciones", photos_path, class: "btn btn-secondary" %>
</div>

<div class="card text-center">
  <div>
    <%= image_tag @photo.image %>
  </div>
  <div class="card">
    <div class="card-body">
      <%= @photo.content %>
    </div>
    <div class="card-footer d-flex justify-content-between">
      <% if user_signed_in? %>
        <%= link_to "Comentar", new_comment_path(@comment), class: "btn btn-primary" %>
      <% end %>
      <% if user_signed_in? && current_user.karina? %>
        <%= link_to "Edit this photo", edit_photo_path(@photo), class: "btn btn-warning" %> 
      <% end %>

      <% if user_signed_in? && current_user.karina? %>
        <%= button_to "Destroy this photo", @photo, method: :delete, class: "btn btn-danger mx-2" %>
      <% end %>
    </div>
  </div>
</div>

<div class="card my-2">
  <h3 class="card-header text-center">Comentarios</h3>
</div>

<% @comments.each do |comment| %>
  <div class="card mb-3">
    <div class="row g-0">
      <div class="col-md-2">
        <%= image_tag comment.user.avatar, class: "avatar-img", style:"height: 200px;" %>
      </div>
      <div class="col-md-8">
        <div class="card-body">
          <h5 class="card-title"><%= comment.user.name %></h5>
          <p class="card-text"><%= comment.content %></p>
          <%= link_to "Ver comentario", comment, class: "btn btn-primary" %>
        </div>
      </div>
    </div>
  </div> 
<% end %>

<div class="my-4">
  <%= link_to "Volver a Publicaciones", photos_path, class: "btn btn-secondary" %>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-dark sticky-top" data-bs-theme="dark">
  <div class="container text-white px-5">
    <%= link_to "Karipic", root_path, class:"navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <div class="nav-item">
        <%= link_to "Publicaciones", photos_path, class:"nav-link active", ariaCurrent:"page" %>
      </div>   
      <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
        <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
          <% if !user_signed_in? %>
              Incia Sesión / Regístrate
          <% else %>
              Hola <%= current_user.name %>
          <% end %>
        </a>
        <ul class="dropdown-menu">
          <% if !user_signed_in? %>
            <li><%= link_to 'Iniciar Sesión', new_user_session_path, class:"dropdown-item" %></li>
            <li><%= link_to 'Registrarse', new_user_registration_path, class:"dropdown-item" %></li>
          <% elsif %>
            <li><%= link_to 'Mi Cuenta', edit_user_registration_path, class:"dropdown-item" %></li>
          <li><%= button_to 'Cerrar Sesión', destroy_user_session_path, class:"dropdown-item", method: :delete, data: {turbo_confirm: "Estás seguro que deseas cerrar sesión?"} %></li>
           <% end %>
        </ul>
      </ul>
    </div>
  </div>
</nav>